# Generated by Django 4.2.7 on 2023-11-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.DecimalField(decimal_places=0, max_digits=3)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
