# Generated by Django 4.2.7 on 2023-11-24 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hex', '0002_avaliador_empresa_equipe_people_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='equipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='people', to='hex.equipe'),
            preserve_default=False,
        ),
    ]
