# Generated by Django 4.2.7 on 2023-11-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hex', '0003_people_equipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='equipe',
        ),
        migrations.AddField(
            model_name='equipe',
            name='people',
            field=models.ManyToManyField(to='hex.people', verbose_name='participantes'),
        ),
    ]
