# Generated by Django 4.2.7 on 2023-11-24 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hex', '0005_remove_equipe_people_remove_equipe_integrantes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='representante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hex.avaliador', verbose_name='Avaliador'),
            preserve_default=False,
        ),
    ]
