# Generated by Django 4.2.7 on 2023-11-24 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hex', '0008_alter_avaliador_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliador',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hex.empresa', verbose_name='empresa'),
        ),
    ]
